### PR TITLE
add a separate target for nmakehlp to help with cross-compilation

### PR DESCRIPTION
**Pull request by nsait-linaro**
This would enable cross-compilation with the following steps.

1. Setup toolchain environment for the host architecture
2. Compile nmakehlp.exe `nmake -f makefile.vc nmakehlp`
3. Setup toolchain environment for the target architecture
4. Compile tcl with SKIP_NMAKEHLP `nmake -f makefile.vc SKIP_NMAKEHLP=TRUE all`

### CODE REVIEW

**Comment by nsait-linaro** [comment]
@nijtmans This is related to the [ticket](https://core.tcl-lang.org/tcl/tktview/d109376adf418ce6d047fb0017d40848272a518f) . Could you help with review please ?

**Comment by nijtmans** [comment]
Slightly better (I hope): [e6bc056435630207](https://core.tcl-lang.org/tcl/info/e6bc056435630207)

**Comment by nsait-linaro** [comment]
> Slightly better (I hope): [e6bc056435630207](https://core.tcl-lang.org/tcl/info/e6bc056435630207)

Many thanks, @nijtmans. That looks much more elegant.

**Comment by nsait-linaro** [comment]
Changed are upstreamed

**Pull request closed without merging**
