### PR TITLE
typedef defintion also present in icc's stddef.h, this prevents redefnintion

### PR DESCRIPTION
**Pull request by rohit-jamuar**
@apnadkarni

### CODE REVIEW

**Comment by apnadkarni** [comment]
I don't believe the github mirror is monitored by any of the core maintainers. I have logged this bug / patch at http://core.tcl.tk/tcl/tktview?name=25deec4e46 (the Tcl ticketing system)

**Comment by rohit-jamuar** [comment]
Thank you, @apnadkarni

**Comment by aryler** [comment]
ICC doesn't define any of those?
Is it good enough to simply add _ICC to the test?

`#if defined(STDC_HEADERS) || defined(__STDC__) || defined(__C99__FUNC__) \
     || defined(__cplusplus) || defined(_MSC_VER)
#include <stddef.h>
#else
typedef int ptrdiff_t;
#endif`

**Comment by dkfellows** [comment]
Looks like `__INTEL_COMPILER` is the correct thing to look for, not `__ICC`. https://sourceforge.net/p/predef/wiki/Compilers/

**Comment by dkfellows** [comment]
@aryler I looked this up, and it only defines those in some operation modes, none of which are we guaranteed to be compiling under. It is all quite horrible.

**Pull request closed without merging**
